### ISSUE TITLE
problem: has no method 'copy'

### ISSUE THREAD

**Issue by lizheGitHub** [rzcoder/node-rsa#27]
node-rsa version : 0.2.13
node js version : v0.8.20

=============================================================================
code:
var NodeRSA = require('node-rsa');
var key = new NodeRSA({b: 512});

var text = 'Hello RSA!';
var encrypted = key.encrypt(text, 'base64');
console.log('encrypted: ', encrypted);
var decrypted = key.decrypt(encrypted, 'utf8');
console.log('decrypted: ', decrypted);

================================================================================
outPut:
[2015-01-05 17:25:22.364] [ERROR] system - error>>>>>>>>>>>>>>>Error: Error during encryption. Original error: TypeError: Object ?拢卯^2U驴茂耟炉?     has no method 'copy'
    at Error (unknown source)
    at NodeRSA.module.exports.NodeRSA.encrypt (/usr/local/node-v0.6.19/epg-crypt/node_modules/node-rsa/src/NodeRSA.js:239:19)
    at test_rsa (/usr/local/node-v0.6.19/epg-crypt/routes/dbSycn.js:86:21)
    at dbSycn.rsaTest (/usr/local/node-v0.6.19/epg-crypt/routes/dbSycn.js:39:3)
    at callbacks (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:272:11)
    at param (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:246:11)
    at param (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:243:11)
    at pass (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:280:5)
    at Object.middleware [as handle] (/usr/local/node-v0.6.19/epg-crypt/node_modules/express/lib/router/index.js:45:10)

**Comment by lizheGitHub** [comment]
node js version : v0.8.20

**Comment by rzcoder** [comment]
Node.js version less than 0.10.x not maintained anyway, please update it first.

**Comment by lizheGitHub** [comment]
I can not update the node.js, which version of the node-rsa is ok?

**Comment by rzcoder** [comment]
Not ever tested, try 0.1.54.
