### ISSUE TITLE
How do use it in nodejs server and  java client?

### ISSUE THREAD

**Issue by xygahs0801** [rzcoder/node-rsa#59]
1.Generate public key and private key then save to database.
2.java client use the public key encrypt the data then use the private key decrypt the data.It is not works.some one help me?
3.error log is here
```
Exception in thread "main" javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:380)
	at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:291)
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
	at javax.crypto.Cipher.doFinal(Cipher.java:2223)
	at com.cjk.mqtt.RSAUtils.decryptByPrivateKey(RSAUtils.java:161)
	at com.cjk.mqtt.Main.main(Main.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by rzcoder** [comment]
No idea.
