### ISSUE TITLE
Export x5c public key

### ISSUE THREAD

**Issue by AlexZeitler** [rzcoder/node-rsa#79]
I'm trying to export a public key of the `x5c` from a [JWS signature](https://tools.ietf.org/html/rfc7515#section-4.1.6).

The cert (`x5c.crt`) looks like this:

```
-----BEGIN CERTIFICATE-----
MIIGdzCCBF+gAwIBAgIJAN5YwmEPNl5RMA0GCSqGSIb3DQEBBQUAMIGDMQswCQYD
VQQGEwJERTEbMBkGA1UECBMSQmFkZW4tV3VlcnR0ZW1iZXJnMRIwEAYDVQQHEwlL
YXJsc3J1aGUxDzANBgNVBAoTBlBETUxhYjESMBAGA1UEAxMJbG9jYWxob3N0MR4w
HAYJKoZIhvcNAQkBFg9pbmZvQHBkbWxhYi5jb20wHhcNMTcwMjEyMjE1NjAxWhcN
MTgwMjEyMjE1NjAxWjCBgzELMAkGA1UEBhMCREUxGzAZBgNVBAgTEkJhZGVuLVd1
ZXJ0dGVtYmVyZzESMBAGA1UEBxMJS2FybHNydWhlMQ8wDQYDVQQKEwZQRE1MYWIx
EjAQBgNVBAMTCWxvY2FsaG9zdDEeMBwGCSqGSIb3DQEJARYPaW5mb0BwZG1sYWIu
Y29tMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtP0dEIltbGhDrYRo
TUmyLmz7rpUcoffUPc992vGP3TvmFkklWV6esW7mzT7l+iBpHmlzW14Ox1b15zGb
UYwpgK9hcpR3cNtNTCfGXmlajWUCdeHpF7YwWTp4P9iQlFwkCY7G3QVBtQs0tcL3
f7j4jbGWy/9EWbmVhKqLxparuhD4wp7OvZiK1uAqTxAbQ56GrmJot49eTPTEcbfJ
5P2ugqbRM41jeXIm4I/OWW7o61pRijT0ECJsmc1qS1MI1jCvgNDAo9QRAvXWfgAy
pVpAEMHGmXRiKb1/i71U8LYIgic602IpWonxhIu6b2yln7I9axCcYv/ZOtPLp2eI
tu3964tO74Wuky2hdwy9oONbRv4XW4Tm1TaxS4yRDa/UbFirwZ5Xh70WhbOqReb9
f/mkEkoFqmVz4l88pgV7YDLduOPyjLLCOImvP4OJoeEDq16JibJ+TfgzBHCPQO8P
CW76GkOo3g2mVbAhs2H7Cb2weljrjIE4qgM3BKZQ2m3WWBPFEng2F7//0kGfVHk0
jcg84gZMjNdj/P0hU6gcBl1gTUs+n3m3+ZO2IV0SmEstwCicQqZZhUP1nBkgnfER
lzeb0PDC572V8aUHZO08KXhptE7rr5uQZy5QdhRz+/zpIOEELOkNc9ybNpaKZ9kR
hhWSz49slQYn0bnoQ2VVFJBZsUsCAwEAAaOB6zCB6DAdBgNVHQ4EFgQUr20CD7t+
VRpVt3zW3dXkVk3wQMwwgbgGA1UdIwSBsDCBrYAUr20CD7t+VRpVt3zW3dXkVk3w
QMyhgYmkgYYwgYMxCzAJBgNVBAYTAkRFMRswGQYDVQQIExJCYWRlbi1XdWVydHRl
bWJlcmcxEjAQBgNVBAcTCUthcmxzcnVoZTEPMA0GA1UEChMGUERNTGFiMRIwEAYD
VQQDEwlsb2NhbGhvc3QxHjAcBgkqhkiG9w0BCQEWD2luZm9AcGRtbGFiLmNvbYIJ
AN5YwmEPNl5RMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggIBALPN+Oy0
SjHgnNlskXgx3nfoFwJTcT/Hsuop5osnDfFKOtebUcqjV1LisINeX3rq7BD7PMTK
Z4RgqDp86OvWNKSebNhmCCR/NUBusReqmpVXjxttrpWyAB0XTAcxB2jaAp34qPqd
UOeUADwt6eduHKf462YiGuB2sE5EmDW0K8waw8eJ6VLoNG98Fw0PPbsryK16mNpl
4o5r9OAKDaFJRE6jfbJXwNeMpQTDYSB+5Nb69TmaDQJe1prE7r5FEeUfg0M8BSe0
Z5KZurVi5+i5pwMeok4pFEsgmJ4Tt+gkBi3SNRaqT7NKGVmNFeO6kDw4KIDs6Va/
Kelr9C1RmLtR1RJ2wjrHbq/o6l+73DlVMFaKn108o7LgbJu0rtKPyrf1nlya4c6b
dT/+1qAC90oiN4mOysNQsrb5XRZ1cjkgOFnWGsilBlHNC2FZ+PZ4KCtLIoASRvCO
AglaS0ByRVsE2qckh3N/oHDTzBtzqFgwmbpHv+6tXVxkXLvadlz6PuWNv3VkivD/
dw6rMrY2W1+tZKtEz5AWw30KMyXntXb2Yc5p6fg9bF367lXZl5oQbr5d41xGi7D0
LQAk95Xj4/Ag29rTybS7nBuPfLiFBUzRc8vhPPgUdc5ji+JqEbX9OnHy+3k1naoM
cK27VF9MUgnAJO6obVz45rZE0o07ZQl5UHaD
-----END CERTIFICATE-----
```

Using `openssl x509 -inform pem -in x5c.crt -pubkey -noout` I get this public key out: 

```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtP0dEIltbGhDrYRoTUmy
Lmz7rpUcoffUPc992vGP3TvmFkklWV6esW7mzT7l+iBpHmlzW14Ox1b15zGbUYwp
gK9hcpR3cNtNTCfGXmlajWUCdeHpF7YwWTp4P9iQlFwkCY7G3QVBtQs0tcL3f7j4
jbGWy/9EWbmVhKqLxparuhD4wp7OvZiK1uAqTxAbQ56GrmJot49eTPTEcbfJ5P2u
gqbRM41jeXIm4I/OWW7o61pRijT0ECJsmc1qS1MI1jCvgNDAo9QRAvXWfgAypVpA
EMHGmXRiKb1/i71U8LYIgic602IpWonxhIu6b2yln7I9axCcYv/ZOtPLp2eItu39
64tO74Wuky2hdwy9oONbRv4XW4Tm1TaxS4yRDa/UbFirwZ5Xh70WhbOqReb9f/mk
EkoFqmVz4l88pgV7YDLduOPyjLLCOImvP4OJoeEDq16JibJ+TfgzBHCPQO8PCW76
GkOo3g2mVbAhs2H7Cb2weljrjIE4qgM3BKZQ2m3WWBPFEng2F7//0kGfVHk0jcg8
4gZMjNdj/P0hU6gcBl1gTUs+n3m3+ZO2IV0SmEstwCicQqZZhUP1nBkgnfERlzeb
0PDC572V8aUHZO08KXhptE7rr5uQZy5QdhRz+/zpIOEELOkNc9ybNpaKZ9kRhhWS
z49slQYn0bnoQ2VVFJBZsUsCAwEAAQ==
-----END PUBLIC KEY-----
```

I tried doing the same using `node-rsa`:

```js
const x5c = fs.readFileSync(path.join(__dirname, 'x5c.crt')).toString();
const key = new NodeRSA([x5c, 'public']);
const exportkey = key.exportKey('public');
```

`exportKey` looks like this:

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuI6TkflCXucwsUb9tuGm
5pfndAUaSHmllcXrIvW5BwBgCxxoMQXdceUS4tkAfNWUV2hHNFdNVVmFQZpyPThI
3ybGiiOq06T+RKDtr5Mj84tD9q03CUbuWPl4mQ2914bKm+yVnovzeP+GpO0/ok1m
ywoYN8Bf0ZKNhFwRkIQUCQtaAW7lUNKZAddhUb3jbBoqO+vJfNHQAdG2Fkz31NKI
igEIBEQIMls646mon4e4ET/eHQSIlVIQcV7HwMFCVnfx449TDjxM7TStBYcM7UWM
DhRJoT21sW6kRPyd+QoJ20y4Lypv0nuMXAtiKytItYw9HjDOFWs9eim7MXiKdYQ8
aQIDAQAB
-----END PUBLIC KEY-----
```

Should this be possible using `node-rsa` or am I doing something wrong here?

**Comment by rzcoder** [comment]
Yeah
`>>> const key = new NodeRSA([x5c, 'public']);`

`const key = new NodeRSA(x5c, 'public');`

**Comment by AlexZeitler** [comment]
Thanks for your response.

When I'm using this:
```const key = new NodeRSA(x5c, 'public');```

I get this error:
```
/Users/alexzeitler/src/nodejwt/node_modules/asn1/lib/ber/reader.js:102
      throw newInvalidAsn1Error('encoding too long');

InvalidAsn1Error: encoding too long
    at module.exports.newInvalidAsn1Error (/Users/alexzeitler/src/nodejwt/node_modules/asn1/lib/ber/errors.js:7:13)
    at Reader.readLength (/Users/alexzeitler/src/nodejwt/node_modules/asn1/lib/ber/reader.js:102:13)
    at Reader.readSequence (/Users/alexzeitler/src/nodejwt/node_modules/asn1/lib/ber/reader.js:135:16)
    at Object.module.exports.publicImport (/Users/alexzeitler/src/nodejwt/node_modules/node-rsa/src/formats/pkcs8.js:148:16)
    at Object.module.exports.detectAndImport (/Users/alexzeitler/src/nodejwt/node_modules/node-rsa/src/formats/formats.js:65:48)
    at NodeRSA.module.exports.NodeRSA.importKey (/Users/alexzeitler/src/nodejwt/node_modules/node-rsa/src/NodeRSA.js:185:22)
    at new NodeRSA (/Users/alexzeitler/src/nodejwt/node_modules/node-rsa/src/NodeRSA.js:75:18)
    at Object.<anonymous> (/Users/alexzeitler/src/nodejwt/parse_pub_from_x5c_rsa.js:8:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rzcoder** [comment]
Are you sure you passed correct key to x5c (is it same from first msg?)
Also check this https://github.com/rzcoder/node-rsa/issues/67#issuecomment-244824452 & this https://github.com/rzcoder/node-rsa/issues/77

**Comment by AlexZeitler** [comment]
Yes, I double checked that I'm using the correct file and I tried the Buffer workaround but the error remains.

**Comment by rzcoder** [comment]
Which node/lib version? Can you provide problem key?

**Comment by AlexZeitler** [comment]
I created a repo including the test key here: https://github.com/AlexZeitler/x5c_check
I tried Node `4.7.0` and `6.9.1` on macOS and `6.2.2` on Ubuntu 16.04.

**Comment by rzcoder** [comment]
Ah, you passing certificate, not an RSA key

**Comment by AlexZeitler** [comment]
Yes, it's a X.509 certificate chain as mentioned in the RFC I linked to in the initial question.

**Comment by rzcoder** [comment]
Node-rsa supports only rsa keys for now.

**Comment by AlexZeitler** [comment]
Do you think it could work using the `x509` package and use it's `x509.parseCert` function. This should extract the publicKey like this:

```
publicKey: {
    algorithm: 'rsaEncryption',
    e: '65537',
    n: '.......' } }
```

 and using `NodeRSA.importKey` I could parse it?

**Comment by rzcoder** [comment]
This should work

```js
const parsedKey = x509.parseCert(path.join(__dirname, 'x5c.crt'));
const key = new NodeRSA();
key.importKey({
    n: new Buffer(parsedKey.publicKey.n, 'hex'),
    e: parseInt(parsedKey.publicKey.e, 10)
}, 'components-public');
const exportedKey = key.exportKey('public');
```

**Comment by AlexZeitler** [comment]
This works great, awesome! Thanks for your help! 👍
